# -*- coding: utf-8 -*-
"""api_config_template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17_CPuo2bAXEzEzcAbeQMAak7bnAsJEXK
"""

pip install google-generativeai python-dotenv

#Import required libraries
import google.generativeai as genai
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
#  Initialize the Gemini model
model = genai.GenerativeModel("gemini-2.5-flash")
print("Gemini model initialized successfully")